services:

  art-postgres:
    image: postgres:latest
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=arthurdb"
    ports:
      - 45432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  art-adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
